### ISSUE TITLE
USER STORY: As a consumer, I can view all products by clicking on all products tab

### ISSUE THREAD

**Issue by colleen-higgins-designs** [blue-geicos/Grace-Shopper#1]
- [x] products db model (#4 )
- [x] all products express Get route (#6)
- [x] all products component (#7)
